# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import engine

class Ui_ExpertSystem(object):
    def setupUi(self, ExpertSystem):

        ExpertSystem.setObjectName("ExpertSystem")
        ExpertSystem.resize(1125, 620)
        self.centralwidget = QtWidgets.QWidget(ExpertSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.caplevel = QtWidgets.QComboBox(self.centralwidget)
        self.caplevel.setGeometry(QtCore.QRect(30, 160, 321, 28))
        self.caplevel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.caplevel.setObjectName("caplevel")
        self.caplevel.addItem('خوب')
        self.caplevel.addItem('متوسط')
        self.caplevel.addItem('ضعیف')
        self.compatitor = QtWidgets.QComboBox(self.centralwidget)
        self.compatitor.setGeometry(QtCore.QRect(400, 250, 321, 28))
        self.compatitor.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.compatitor.setObjectName("compatitor")
        self.compatitor.addItem('خوب')
        self.compatitor.addItem('متوسط')
        self.compatitor.addItem('ضعیف')
        self.future = QtWidgets.QComboBox(self.centralwidget)
        self.future.setGeometry(QtCore.QRect(30, 250, 321, 28))
        self.future.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.future.setObjectName("future")
        self.future.addItem('افزایش فروش')
        self.future.addItem('حفظ میزان فروش')
        self.future.addItem('حذف محصول یا کاهش فروش')
        self.salesrate = QtWidgets.QComboBox(self.centralwidget)
        self.salesrate.setGeometry(QtCore.QRect(400, 160, 321, 28))
        self.salesrate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.salesrate.setObjectName("salesrate")
        self.salesrate.addItem('خوب')
        self.salesrate.addItem('متوسط')
        self.salesrate.addItem('ضعیف')
        self.saleslevel = QtWidgets.QComboBox(self.centralwidget)
        self.saleslevel.setGeometry(QtCore.QRect(780, 160, 321, 28))
        self.saleslevel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.saleslevel.addItem('خوب')
        self.saleslevel.addItem('متوسط')
        self.saleslevel.addItem('ضعیف')
        self.saleslevel.setObjectName("saleslevel")
        self.caprate = QtWidgets.QComboBox(self.centralwidget)
        self.caprate.setGeometry(QtCore.QRect(780, 250, 321, 28))
        self.caprate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.caprate.addItem('خوب')
        self.caprate.addItem('متوسط')
        self.caprate.addItem('ضعیف')
        self.caprate.setObjectName("caprate")
        self.resulttext = QtWidgets.QTextEdit(self.centralwidget)
        self.resulttext.setGeometry(QtCore.QRect(30, 370, 1061, 221))
        self.resulttext.setObjectName("resulttext")
        self.Redult = QtWidgets.QPushButton(self.centralwidget)
        self.Redult.setGeometry(QtCore.QRect(400, 303, 321, 41))
        self.Redult.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Redult.setAutoDefault(False)
        self.Redult.setObjectName("Redult")
        self.Redult.clicked.connect(self.act_result)
        #########################################################
        self.new_rule = QtWidgets.QPushButton(self.centralwidget)
        self.new_rule.setGeometry(QtCore.QRect(30, 303, 321, 41))
        self.new_rule.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_rule.setAutoDefault(False)
        self.new_rule.setObjectName("new_rule")
        self.new_rule.clicked.connect(self.insert_new_rul)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 91, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r'lib\sqlite3\logo.jpg'))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(790, 130, 311, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 130, 311, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 311, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(790, 220, 311, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 220, 311, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 220, 311, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.name = QtWidgets.QTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(860, 50, 241, 31))
        self.name.setObjectName("name")
        ExpertSystem.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ExpertSystem)
        self.statusbar.setObjectName("statusbar")
        ExpertSystem.setStatusBar(self.statusbar)

        self.retranslateUi(ExpertSystem)
        QtCore.QMetaObject.connectSlotsByName(ExpertSystem)

    def act_result(self):
        inference = engine.Inference()
        result = inference.knowledgebase_inference(self.saleslevel.currentText(), self.salesrate.currentText(), self.caplevel.currentText()
                                               ,self.caprate.currentText(), self.compatitor.currentText(), self.future.currentText())
        self.resulttext.setText(result)

    def insert_new_rul(self):
        inference = engine.Inference()
        re = inference.insert_rule(self.saleslevel.currentText(), self.salesrate.currentText(), self.caplevel.currentText()
                                               ,self.caprate.currentText(), self.compatitor.currentText(), self.future.currentText(), self.resulttext.toPlainText())
        self.resulttext.setText(re)

    def retranslateUi(self, ExpertSystem):
        _translate = QtCore.QCoreApplication.translate
        ExpertSystem.setWindowTitle(_translate("ExpertSystem", "MainWindow"))
        self.Redult.setText(_translate("ExpertSystem", "دریافت نتیجه"))
        self.new_rule.setText(_translate("ExpertSystem", "ایجاد قانون"))
        self.label_2.setText(_translate("ExpertSystem", "سطح فروش در بازه زمانی موردنظر"))
        self.label_3.setText(_translate("ExpertSystem", "سطح پیشرفت فروش نسبت بازه زمانی قبلی"))
        self.label_4.setText(_translate("ExpertSystem", "نرخ جذب مشتری در بازه زمانی موردنظر"))
        self.label_5.setText(_translate("ExpertSystem", "نرخ جذب مشتری نسبت به زمانی قبلی"))
        self.label_6.setText(_translate("ExpertSystem", "شرایط رقیبان در بازار در بازه زمانی مورد نظر"))
        self.label_7.setText(_translate("ExpertSystem", "سطح گسترش بازار محصول در بازه زمانی بعدی"))
        self.name.setHtml(_translate("ExpertSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">برنامه نویس : محمدصادق آبادی‌جو</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExpertSystem = QtWidgets.QMainWindow()
    ui = Ui_ExpertSystem()
    ui.setupUi(ExpertSystem)
    ExpertSystem.show()
    sys.exit(app.exec_())
